# Imagem
FROM phpmyadmin/phpmyadmin:latest

# Propriedade
MAINTAINER Danilo D. de Godoy <danilo.doring@gmail.com>

# Variaveis de Ambiente
ENV PMA_ARBITRARY=0
ENV PMA_USER=root
ENV PMA_PASSWORD=r0oTpWd!