FROM mariadb:10.2

# Propriedade
MAINTAINER Danilo D. de Godoy <danilo.doring@gmail.com>

# Data e Hora
ENV TZ=America/Sao_Paulo

# Variaveis de Ambiente
ENV MYSQL_ROOT_PASSWORD_FILE=/run/secrets/dbroot

# Porta
EXPOSE 3306